POST http://localhost:3000/api/user/update HTTP/1.1
Content-Type: application/json
Cookie: token=j%3A%226481a18937cdcdc9d541b7f4%22; Path=/; HttpOnly

{
    "name": "test2",
    "email": "test2@gmail.com"
}